// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByatIZW_CCIeTvgG7S9yGFwIG_bcE-oPU',
    appId: '1:582630173242:web:cc7b376f8afc4c78d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    authDomain: 'capston-5713f.firebaseapp.com',
    databaseURL: 'https://capston-5713f-default-rtdb.firebaseio.com',
    storageBucket: 'capston-5713f.appspot.com',
    measurementId: 'G-ZB6YS1XQJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1DQUIFOuN3UPJdWBVfvAJ9ngugnZ0FE',
    appId: '1:582630173242:android:db5e94c0e9764080d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    databaseURL: 'https://capston-5713f-default-rtdb.firebaseio.com',
    storageBucket: 'capston-5713f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpLjJL27hF41xuXf6cS62mtd8vfA9_uc',
    appId: '1:582630173242:ios:c8fc29ac56169a91d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    databaseURL: 'https://capston-5713f-default-rtdb.firebaseio.com',
    storageBucket: 'capston-5713f.appspot.com',
    iosClientId: '582630173242-fvq7c42frt0dbkhbmnm83olaqiu4911b.apps.googleusercontent.com',
    iosBundleId: 'com.example.musik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpLjJL27hF41xuXf6cS62mtd8vfA9_uc',
    appId: '1:582630173242:ios:c8fc29ac56169a91d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    databaseURL: 'https://capston-5713f-default-rtdb.firebaseio.com',
    storageBucket: 'capston-5713f.appspot.com',
    iosClientId: '582630173242-fvq7c42frt0dbkhbmnm83olaqiu4911b.apps.googleusercontent.com',
    iosBundleId: 'com.example.musik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByatIZW_CCIeTvgG7S9yGFwIG_bcE-oPU',
    appId: '1:582630173242:web:df3efc59869b99a6d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    authDomain: 'capston-5713f.firebaseapp.com',
    databaseURL: 'https://capston-5713f-default-rtdb.firebaseio.com',
    storageBucket: 'capston-5713f.appspot.com',
    measurementId: 'G-Y7TXPML2M1',
  );
}
